### ISSUE TITLE
DimeScopeFlutter to support registering mocks in widget tests

### ISSUE THREAD

**Issue by davejlin** [magillus/dart_dime#16]
Please add support to allow registering mocks for testing of widgets using DimeScopeFlutter.

```
class MyScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DimeScopeFlutter(
      scopeName: 'scope',
      modules: [
        MyModule(),
      ],
      child: Scaffold(
        body: MyWidget(),
      ),
    );
  }
}
```

**Comment by magillus** [comment]
From our email conversation:
I assume it is about `MyModule` override a root scope dependency with something else.

**Comment by magillus** [comment]
I tried this and it seems like the lookup for instance goes through local scope first. 
So my original idea to fix it wasn't needed.

@davejlin Do you have sample code how you get the instance of the object inside `MyWidget` ?
Do you use something like this:
```
    final scope = DimeFlutter.scopeOf(context);
    final titleText = scope.get();
```
